config/routes.rb
Betyoulose::Application.routes.draw do

  resources :purchases, :only => [:index, :show, :destroy] do
    get 'payment_info'
  end  

  resources :payment_notifications

  match 'wagers/my_wagers' => 'wagers#my_wagers', :as => :my_wagers
  match 'bets/my_bets' => 'bets#my_bets', :as => :my_bets
  
  resources :wallets, :only => [:show] do
    get 'buy'
    post 'purchase'
    resources :transactions, :only => [:index]
  end  

  resources :bets do
    resources :wagers, :except => [:index, :show, :create, :new, :destroy]
  end  

  devise_for :users
  
  match 'bets/:bet_id/wagers/:against' => 'wagers#bet_now', :as => :bet_now
  root :to => "bets#index"

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  attr_accessible :title, :description, :end_date, :wager_amount, :verify_description, :verified, :confirmed, :user_id, :display_name, :wagers_count, :status
  has_many :transactions
  has_many :wagers
  validates_presence_of :title, :description, :end_date, :wager_amount, :verify_description, :display_name
  validates_length_of :title, :minimum => 2
  validates_length_of :title, :maximum => 80
  validates_length_of :display_name, :minimum => 2
  validates_length_of :display_name, :maximum => 20
  validates_length_of :description, :minimum => 20
  validates_length_of :description, :maximum => 500
  validates_length_of :verify_description, :minimum => 20
  validates_length_of :verify_description, :maximum => 500
  scope :standard, :order => "verified ASC", :conditions => ["end_date >= ? AND confirmed = ?", Time.zone.now, true]  
  validate do |bet|
      bet.errors.add(:end_date, "end date must be after now") if bet.end_date < Time.now
      bet.errors.add(:wager_amount, "not enough credits for this wager amount") if (bet.wager_amount && bet.wager_amount > bet.user.wallet.credits)
  end
  
  def total_wagers
    if self.wagers.size < 1
      return 1
    else
      return self.wagers.size
    end    
  end  
  
  def total_value
    if self.wagers.size < 1
      return self.wager_amount
    else
      self.wagers.sum(:credits)  
    end  
  end  
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def assign_winnings(result)
    if result == "Won" 
      indv_amount = self.wagers.sum(:credits).to_i / self.wagers.bets_for.size 
      for bet in self.wagers.bets_for
        bet.user.wallet.credits += indv_amount
        bet.user.wallet.save
        bet.user.wallet.transactions.create!(:description => "Assigned winnings of #{indv_amount.to_s} credits to user.")
      end
    elsif result == "Lost"
      indv_amount = self.wagers.sum(:credits).to_i /  self.wagers.bets_against.size if result == false
      for bet in self.wagers.bets_against
        bet.user.wallet.credits += indv_amount
        bet.user.wallet.save
        bet.user.wallet.transactions.create!(:description => "Assigned winnings of #{indv_amount.to_s} credits to user.")
      end   
    end
  end  
  
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  respond_to :html, :xml, :json, :js
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :authenticate_admin, :only => [:edit, :destroy]
  before_filter :find_bet, :except => [:index, :new, :create, :my_bets]
  
  def index
    if !params[:search]
      params["search"] = {"meta_sort" => "wagers_count.desc"}
    end  
    @search = Bet.standard.search(params[:search])
    @bets = @search.paginate(:per_page => 2, :page => params[:page])
  end

  def show
    @wagers = @bet.wagers.order("created_at DESC").paginate(:per_page => 5, :page => params[:page])
  end

  def new
    @bet = Bet.new
    @bet.end_date = 3.days.from_now
    respond_with(@bet)
  end

  def create
    @bet = Bet.new(params[:bet])
    @bet.confirmed = true if current_user.admin?
    @bet.user = current_user
    if @bet.save
      @bet.wagers.create(:credits => @bet.wager_amount, :against => false, :user_id => @bet.user.id)
      @bet.user.wallet.credits -= @bet.wager_amount
      @bet.user.wallet.save
      @bet.user.wallet.transactions.create!(:description => "Created Bet for #{@bet.wager_amount.to_s} credits.", :bet_id => @bet)
      respond_with(@bet, :notice => "Successfully created bet.")
    else
      render :action => 'new'
    end  
  end

  def edit
  end

  def update
    old_status = @bet.status
    @bet.verified = true if params[:bet][:status] != 'Undecided'
    if @bet.update_attributes(params[:bet])
      @bet.assign_winnings(@bet.status) if @bet.status != old_status
      respond_with(@bet, :notice  => "Successfully updated bet.")
    else
      render :action => 'edit'
    end
  end

  def destroy
    @bet.destroy
    respond_with(@bet, :notice => "Successfully destroyed bet.")
  end
  
  def my_bets  
    @bets = current_user.bets.paginate(:per_page => 2, :page => params[:page])
  end
  
  private 
  
  def find_bet
    @bet = Bet.find(params[:id])
  end  
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_bet.html.erb
<div id="bet-<%= bet.id %>" class="bet-panel-small <%= bet.status.downcase %> <%= cycle("even", "odd") -%>">
	<div class="bet-title"><%= link_to bet.title, bet, :title => "Show details of " + bet.title + " bet"  %></div>
	<div class="bet-description"><%= truncate(bet.description, :length => 80) %></div>
	<div class="bet-end-date">Ends <%= bet.end_date.strftime("%a %d %b %Y") %></div>
	<div class="bet-wager-info">
		<div class="bet-wager-amount">Total bets : <%= bet.total_wagers %> worth <%= bet.total_value %> credits</div>
		<div class="bet-wager-amount"><%= bet.wagers.bets_for.size %> bets for - <%= bet.wagers.bets_against.size %> bets against</div>
		<div class="bet-wager-amount">Default wager amount : <%= bet.wager_amount %> credits</div>
	</div>
	<div class="bet-display-name-line"><span class="bet-display-name"><%= bet.display_name %></span> says <%= APP_CONFIG["application_name"] %>!</div>
</div>	

app/views/bets/_bets.html.erb
<div id="previews">
	
	<p class="sort-links">
	  Sort by:
	  <%= sort_link @search, :end_date, 'Ending' %> |
	  <%= sort_link @search, :created_at, 'Newest' %> | 
	  <%= sort_link @search, :wagers_count, 'Popularity' %>
	</p>
	
	<% if @bets.size == 0 %>
		&nbsp
	<% end %>
	<%= render @bets %>
	<div class="clear"></div>
	<%= will_paginate @bets %>
	
</div>

app/views/bets/_form.html.erb
<%= semantic_form_for @bet do |f| %>
  <%= error_div_for @bet %>
  <%= f.semantic_errors  %>
  <%= f.inputs do %>
	<%= f.input :title %>
	<%= f.input :description, :input_html => { :rows => 10, :cols => 10, :maxlength => 500 } %>
	<%= f.input :display_name, :hint => "Choose a name that the person you are betting against will recognize i.e BigTalker2011" %>
	<%= f.input :end_date, :start_date => Time.now.year, :include_blank => false  %>
	<%= f.input :wager_amount %>
	<%= f.input :verify_description, :label => "Verification", :hint => "Describe how we can verify the winner", :input_html => { :rows => 10, :cols => 10, :maxlength => 500 } %>
	<% if current_user.try(:admin?) %>	
		<%= f.input :confirmed %>
		<%= f.input :status, :as => :select, :collection => [["Undecided", "Undecided"], ["Won", "Won"], ["Lost", "Lost"]], :include_blank => false %>
	<% end%>
  <% end %>	
  <%= f.buttons %>
<% end %>

app/views/bets/_my_bets.html.erb
<div id="previews" class="wagers"> 
	
	<% if @bets.size == 0 %>
		&nbsp
	<% end %>
	
<% for bet in @bets do %>
	<%= bet.title %> - Status : <span class="bold"><%= bet.status %></span> created on  <%= bet.created_at.strftime("%a %d %b %Y %I:%M %p") %><br />
<% end %>	

<%= will_paginate @bets, :params => {:controller => "bets", :action => "my_bets"} %>
</div>

app/views/bets/_wagers.html.erb
<div id="previews"> 
	
	<% if @wagers.size == 0 %>
		&nbsp
	<% end %>
	
<% for wager in @wagers do %>
	<%= wager.user.display_name %> bet <%= wager.credits %> on  <%= wager.created_at.strftime("%a %d %b %Y %I:%M %p") %><br />
<% end %>	

<%= will_paginate @wagers, :params => {:controller => "bets", :action => "show"} %>
</div>

app/views/bets/edit.html.erb
<% title "Edit Bet" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @bet %> |
  <%= link_to "View All", bets_path %>
</p>

app/views/bets/index.html.erb
<% title "Bets", show_title = false %>

<div class="intro-text">
	Arguing with someone that thinks they're right when they're not? Tell them to put their money where their mouth is! Create your bet, put some credits on it, and dare them to bet against you. You can each bet as many times as you want, and other people can join in if they want. <%= link_to "Create a New Bet now", new_bet_path, :class => "red-text" %>
</div>

<div class="clear"></div>
	
<div class="search">	
	<%= form_for @search do |f| %>
	  <p>
	    <%= f.label :title_or_description_or_display_name_contains, 'Search' %>
	    <%= f.search_field :title_or_description_or_display_name_contains, :placeholder => "Search title, description and person" %>
		<%= f.submit "Search" %>
	  </p>
	<% end %>
</div>

<div class="clear"></div>

<%= render 'bets' %>

app/views/bets/index.js.erb
if ($("#previews").length>0)
{
	$("#previews").replaceWith("<%= escape_javascript(render 'bets') %>");
}

app/views/bets/my_bets.js.erb
if ($("#previews").length>0)
{
	$("#previews").replaceWith("<%= escape_javascript(render 'my_bets') %>");
}

app/views/bets/new.html.erb
<% title "New Bet" %>

<%= render 'form' %>

<p><%= link_to "Back to List", bets_path %></p>

app/views/bets/show.html.erb
<% title @bet.title %>

<div class="center-inner">
	
	<div id="bet-<%= @bet.id %>" class="bet-panel">
		<div class="bet-title"><%= @bet.title %></div>
		<div class="bet-description"><%= @bet.description %></div>
		<div class="bet-end-date">Ends <%= @bet.end_date.strftime("%a %d %b %Y") %></div>
		<div class="bet-wager-amount">Total bets : <%= @bet.total_wagers %> worth <%= @bet.total_value %> credits</div>
		<div class="bet-wager-amount"><%= @bet.wagers.bets_for.size %> bets for - <%= @bet.wagers.bets_against.size %> bets against</div>
		<div class="bet-wager-amount">Default wager amount : <%= @bet.wager_amount %> credits</div>
		<div class="bet-display-name">created by <%= @bet.display_name %></div>
		<div class="bet-verify-description">How to verify bet : <%= auto_link(@bet.verify_description, :link => :urls, :html => { :target => '_blank', :rel => 'nofollow' }) %></div>	
		<div class="bet-status">Status : <%= @bet.status %></div>
		<% if current_user.try(:admin?) %>	
			<div class="bet-verified">Verified : <%= @bet.verified %></div>
			<div class="bet-confirmed">Confirmed : <%= @bet.confirmed %></div>			
			<div class="bet-admin-links">
				<%= link_to "Edit", edit_bet_path(@bet) %> |
				<%= link_to "Destroy", @bet, :confirm => 'Are you sure?', :method => :delete %>
			</div>
		<% end %>
	</div>
	
	<div class="clear"></div>
	
	<% if @bet.status == "Undecided" %>
		<div class="wager-links standard-padding">
			<% if user_signed_in? %>
				<%= link_to "Bet " + @bet.wager_amount.to_s + " that he's wong", bet_now_path(@bet, :against => 'true'), :confirm => 'Are you sure?', :class => "red-text", :remote => true %> or <%= link_to "Bet " + @bet.wager_amount.to_s + " that he's right", bet_now_path(@bet, :against => 'false'), :confirm => 'Are you sure?', :class => "red-text", :remote => true %>
			<% else %>
				<%= link_to "Bet " + @bet.wager_amount.to_s + " that he's wong", user_session_url, :class => "red-text" %> or <%= link_to "Bet " + @bet.wager_amount.to_s + " that he's right", user_session_url, :class => "red-text" %>
			<% end %>
		</div>
	<% end %>
	
	<h3>Wagers Placed</h3>
	<%= render 'wagers' %>
	
</div>

app/views/bets/show.js.erb
if ($("#previews").length>0)
{
	$("#previews").replaceWith("<%= escape_javascript(render 'wagers') %>");
}