config/routes.rb
Betyoulose::Application.routes.draw do

  resources :purchases, :only => [:index, :show, :destroy] do
    get 'payment_info'
  end  

  resources :payment_notifications

  match 'wagers/my_wagers' => 'wagers#my_wagers', :as => :my_wagers
  match 'bets/my_bets' => 'bets#my_bets', :as => :my_bets
  
  resources :wallets, :only => [:show] do
    get 'buy'
    post 'purchase'
    resources :transactions, :only => [:index]
  end  

  resources :bets do
    resources :wagers, :except => [:index, :show, :create, :new, :destroy]
  end  

  devise_for :users
  
  match 'bets/:bet_id/wagers/:against' => 'wagers#bet_now', :as => :bet_now
  root :to => "bets#index"

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  respond_to :html, :xml, :json, :js
  before_filter :find_purchase, :only => [:show, :destroy]
  before_filter :authenticate_admin
  
  def index
    if !params[:search]
      params["search"] = {"meta_sort" => "id.desc"}
    end
    @search = Purchase.search(params[:search])
    @purchases = @search.paginate(:per_page => 2, :page => params[:page])
  end

  def show
  end

  def destroy
    @purchase.destroy
    redirect_to purchases_url, :notice => "Successfully destroyed purchase."
  end
  
  def payment_info
    purchase = Purchase.find(params[:purchase_id])
    @payment_notification = purchase.payment_notification
  end  
  
  private
  
  def find_purchase
    @purchase = Purchase.find(params[:id])
  end  
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_payment_notification.html.erb
<h3>Information</h3>

<ul>
<% @payment_notification.params.each do |key, value| %>
  <li><%= key %>: <%= value %></li>
<% end %>
</ul>

app/views/purchases/_purchase.html.erb
<div id="purchase-<%= purchase.id %>" class="purchase <%= purchase.status %>">
	<div class="row-item row-item-short"><%= purchase.id %></div>
	<div class="row-item border-left row-item-long"><%= purchase.user.display_name %></div>
	<div class="row-item border-left row-item-long"><%= purchase.user.email %></div>
	<div class="row-item border-left row-item-short"><%= purchase.amount %></div>
	<div class="row-item border-left row-item-short"><%= number_to_currency(purchase.value, :unit => def_cur) %></div>
	<div class="row-item border-left row-item-long"><%= purchase.created_at.strftime("%d/%m/%Y %I:%M %p")  %></div>
	<div class="row-item border-left row-item-long"><%= purchase.purchased_at ? purchase.purchased_at.strftime("%d/%m/%Y %I:%M %p") : "Waiting"  %></div>
	<div class="row-item border-left row-item-long bold"><%= purchase.payment_notification ? purchase.payment_notification.status : "Waiting" %></div>
	<div class="left"><%= link_to "info", purchase_payment_info_path(purchase), :remote => true %></div>
</div>

app/views/purchases/_purchases.html.erb
<div id="pagination">
	
	<p class="sort-links">
	  Sort by:
	  <%= sort_link @search, :id, 'Purchase Id' %> |
	  <%= sort_link @search, :created_at, 'Date Started' %> |
	  <%= sort_link @search, :user_display_name, 'User Name' %> | 
	  <%= sort_link @search, :user_email, 'User Email' %> | 
	  <%= sort_link @search, :payment_notification_status, 'Status' %>
	</p>
	
	<%= render @purchases %>

	<div class="clear"></div>

	<%= will_paginate @purchases %>
	
</div>

app/views/purchases/index.html.erb
<% title "Purchases" %>

<div class="left">
	<h3>Search</h3>
	<%= form_for @search do |f| %>
	  <p>
	    <%= f.search_field :id_eq, :placeholder => "Search Transaction ID's" %> and/or 
	    <%= f.search_field :user_display_name_or_user_email_contains, :placeholder => "Search user name or email" %>
		<%= f.submit "Search" %>
	  </p>
	<% end %>
</div>

<div class="clear"></div>

<%= render 'purchases' %>


<div id="info-box" class="info-box rounded-border"><h3>Information</h3></div>

<div class="clear"></div>

app/views/purchases/index.js.erb
if ($("#pagination").length>0)
{
	$("#pagination").replaceWith("<%= escape_javascript(render 'purchases') %>");
}

app/views/purchases/payment_info.js.erb
if ($("#info-box").length>0)
{
	$("#info-box").html("<%= escape_javascript(render 'payment_notification') %>");
}

app/views/purchases/show.html.erb
<% title "Purchase" %>

<%= render @purchase %>

<div class="clear"></div>