config/routes.rb
Betyoulose::Application.routes.draw do

  resources :purchases, :only => [:index, :show, :destroy] do
    get 'payment_info'
  end  

  resources :payment_notifications

  match 'wagers/my_wagers' => 'wagers#my_wagers', :as => :my_wagers
  match 'bets/my_bets' => 'bets#my_bets', :as => :my_bets
  
  resources :wallets, :only => [:show] do
    get 'buy'
    post 'purchase'
    resources :transactions, :only => [:index]
  end  

  resources :bets do
    resources :wagers, :except => [:index, :show, :create, :new, :destroy]
  end  

  devise_for :users
  
  match 'bets/:bet_id/wagers/:against' => 'wagers#bet_now', :as => :bet_now
  root :to => "bets#index"

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  attr_accessible :credits, :user_id
  has_one :user
  has_many :transactions
  validates_numericality_of :credits
    
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  respond_to :html, :xml, :json, :js
  before_filter :get_wallet
  before_filter :authenticate_user!
  
  def show  
    @transactions = current_user.wallet.transactions.order("created_at DESC").paginate(:per_page => 5, :page => params[:page])
  end
  
  def buy
    @purchase = Purchase.new(:amount => 50)
  end
  
  def purchase
      @purchase = Purchase.new(params[:purchase])
      @purchase.assign_credit_value if @purchase.amount
      @purchase.user = current_user
      @purchase.wallet = current_user.wallet
      if @purchase.save
        @wallet.transactions.create!(:description => "Attempted to purchase #{@purchase.amount.to_s} credits.")
        redirect_to @purchase.paypal_url(payment_notifications_url,payment_notifications_url)  
      else
        flash[:notice] = "Value must be a number greater than 50 and less than 500"
        render :action => 'buy'
    end
  end    
    
  
  private
  
  def get_wallet
    @wallet = current_user.wallet
  end  
  
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_admin-links.html.erb
<div class="rounded-border right standard-padding">
	<h3>Admin Links</h3>
	<ul>
		<li><%= link_to "All Purchases", purchases_url %></li>
	</ul>	
</div>

app/views/wallets/_form.html.erb
<%= form_for @purchase, :as => :purchase, :url => wallet_purchase_path do |f| %>
	<%= error_messages_for(@purchase) %>
	
	<p><%= f.label :amount, "Amount" %>
	   <%= f.number_field :amount, :min => 50, :max => 500, :step => 50 %>
	</p>
	<p>
	   <%= f.submit 'Buy' %>
	</p>
	
<% end %>

app/views/wallets/_transactions.html.erb
<div id="previews"> 
	
	<% if @transactions.size == 0 %>
		&nbsp
	<% end %>
	
<% for transaction in @transactions do %>
	<%= transaction.description %> on <%= transaction.created_at.strftime("%a %d %b %Y %I:%M %p") %><br />
<% end %>	

<%= will_paginate @transactions, :params => {:controller => "wallets", :action => "show"} %>
</div>

app/views/wallets/buy.html.erb
<% title "Purchase Credits" %>

<p>You can purchase credits to create new bets or bet on existing bets. After clicking <em>'buy'</em> you will be taken through to PayPal to complete your purchase. Ensure you click through to 'Return to BetYouLose' to ensure a quicker confirmation of your purchase.</p>
<p>Credits are sold at 50 credits for <%= number_to_currency(50  * get_credit_value, :unit => def_cur) %>, or roughly <%= number_to_currency(50  * get_credit_value * 6.8, :unit => "R") %> depending on the exchange rate on the given day. Minimum purchase is 50 credits and Maximum is 500. Credits must be bought in multiples of 50</p>
<%= render 'form' %>

app/views/wallets/show.html.erb
<% title "My Wallet" %>

<div class="thin-border credit-box left standard-padding">
<h3>My Credits </h3>	

<p>
  <strong>Credits:</strong>
  <%= @wallet.credits %><br /> 
  <span class="small-text italics">worth approx. <%= number_to_currency(@wallet.credits  * get_credit_value, :unit => "$") %></span>
</p>
<p><%= link_to "Buy Credits >>", wallet_buy_path(current_user.wallet), :class => "red-text" %></p>

</div>

<% if current_user.try(:admin?) %>	
	<%= render 'admin-links' %>
<% end %>

<div class="clear"></div>

<div class="my-links bold">
  	<%= link_to "Transactions", {:controller => "wallets", :action => "show"}, :remote => true %>  | 
	<%= link_to "My Bets", my_bets_path, :remote => true %> | 
	<%= link_to "My Betting History", my_wagers_path, :remote => true %>
</div>

<%= render 'transactions' %>

app/views/wallets/show.js.erb
if ($("#previews").length>0)
{
	$("#previews").replaceWith("<%= escape_javascript(render 'transactions') %>");
}